### ISSUE TITLE
[Feat]: Random Server Name

### ISSUE THREAD

**Issue by TheVisual** [zer0def/undetected-frida#2]
https://github.com/Exo1i/MagiskHluda/pull/7

Similar to this but random for each build of module?

https://github.com/zer0def/undetected-frida/releases/download/16.4.5/undetected-frida-server-16.4.5-android-arm64.xz

Example dgdsftgres (random name) instead of `florida-server`

**Comment by zer0def** [comment]
I like your idea from Exo1i's issue tracker more, since you still need to point to the binary somehow. Random names generally are a better idea when you can generate them at runtime.

**Comment by zer0def** [comment]
Oh yeah, and you don't need to keep the downloaded file's name intact, when using outside of the Magisk/KSU module, so there's no reason for me to impose some wild naming scheme, when the user can do it for themselves.
