### ISSUE TITLE
Failed to spawn: agent connection closed unexpectedly

### ISSUE THREAD

**Issue by cloud-jie** [zer0def/undetected-frida#7]
![image](https://github.com/user-attachments/assets/1ae50c7c-cff7-462f-9543-bab8859d29f8)
![image](https://github.com/user-attachments/assets/38bd0676-664f-41bd-8412-c5186616ab7b)

The app has no protection, it's just a test demo

**Comment by deezph** [comment]
> ![image](https://private-user-images.githubusercontent.com/63632785/358699150-1ae50c7c-cff7-462f-9543-bab8859d29f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTE3MjAsIm5iZiI6MTcyMzkxMTQyMCwicGF0aCI6Ii82MzYzMjc4NS8zNTg2OTkxNTAtMWFlNTBjN2MtY2ZmNy00NjJmLTk1NDMtYmFiODg1OWQyOWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE2MTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNmY5MTgzMmJhOTAzNDdkYTk0ZDcyZjEwZjgwYzJhNTZhYjkxN2FmNTIzZWI5NWMzMjdhNzhiNmFkMmQxY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iIGmDsM2moEI8VcqJvjW8R6JfJyPRWnklOTNTRR6zOU) ![image](https://private-user-images.githubusercontent.com/63632785/358699203-38bd0676-664f-41bd-8412-c5186616ab7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTE3MjAsIm5iZiI6MTcyMzkxMTQyMCwicGF0aCI6Ii82MzYzMjc4NS8zNTg2OTkyMDMtMzhiZDA2NzYtNjY0Zi00MWJkLTg0MTItYzUxODY2MTZhYjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE2MTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOWVlNTExYTZhYzQ1YzdiZGRkMjA3YmViNzVmN2M4OGFjOWU2NzgyMzIxYjZhYmM5ZWNiNDU3YzUwZDdkOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PtVfoaHRLXak7b5wX48qWF3UFW6VFGoHbQKGuth_fzA)
> 
> The app has no protection, it's just a test demo

same

**Comment by zer0def** [comment]
Try both 16.4.9 and 16.4.10, report back outcomes.

**Comment by deezph** [comment]
> Try both 16.4.9 and 16.4.10, report outcomes back.
 frida not  responding 
 take a while and get this msg : Failed to spawn: timeout was reached

**Comment by vellrya** [comment]
@zer0def 16.4.9:
Failed to enumerate processes: agent connection closed unexpectedly.
Android 9, OnePlus 3.

Official version and Florida works, but can't pass the check in the application I'm interested in. It would be interesting to try your solution)

**Comment by zer0def** [comment]
Solved by pulling AsenOsen's patches.

**Comment by vellrya** [comment]
I apologize if my previous post contained unnecessary information)

I downloaded a new version from the release section, unfortunately the error is repeated.
![image](https://github.com/user-attachments/assets/b5e04c48-80c9-4b42-9a2b-cc4c9929bdd7)

I would also like to add that even running undetected frida-server on a device, is determined by this app, for example: https://github.com/fatalSec/android_in_app_protections (with bypass from author attached)

e.g. by netstat contains frida-server
![image](https://github.com/user-attachments/assets/10e44453-a493-4c1d-b373-cc0bf6dd290c)

Does it work as intended?

**Comment by zer0def** [comment]
You were lured to this repo exclusively by promises contained in it's name, huh?
