### ISSUE TITLE
invalid address

### ISSUE THREAD

**Issue by deezph** [zer0def/undetected-frida#8]
a03:/ $ cd /data/local/tmp
a03:/data/local/tmp $ ls
undetected-frida-server-16.4.10-android-arm64
a03:/data/local/tmp $ su
a03:/data/local/tmp # ./undetected-frida-server-16.4.10-android-arm64 &
[1] 13465
a03:/data/local/tmp # {"type":"error","description":"Error: invalid address","stack":"Error: invalid address\n    at Object.value [as patchCode] (frida/runtime/core.js:207:1)\n    at ln (frida/node_modules/frida-java-bridge/lib/android.js:1215:1)\n    at pn.activate (frida/node_modules/frida-java-bridge/lib/android.js:1281:1)\n    at mn.replace (frida/node_modules/frida-java-bridge/lib/android.js:1329:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1189:1)\n    at Function.set [as implementation] (frida/node_modules/frida-java-bridge/lib/class-factory.js:1103:1)\n    at installLaunchTimeoutRemovalInstrumentation (/internal-agent.js:435:37)\n    at init (/internal-agent.js:51:3)\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250:1)","fileName":"frida/runtime/core.js","lineNumber":207,"columnNumber":1}

**Comment by zer0def** [comment]
Your spam is unwelcome here.
